import os

__version__ = "0.0.0"

class Package:
  def __init__(self):
    self.mods = []

class Mod:
  pass

def package():
  pkg = Package()
  pkg.path = os.path.dirname(__file__)
  pkg.name = os.path.basename(pkg.path)
  pkg.astro_version = "0.0.4"
  pkg.glia_version = "0.1.1"

  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Leak__0
  modglia__dbbs_mod_collection__Leak__0 = Mod()
  modglia__dbbs_mod_collection__Leak__0.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Leak__0.asset_name = 'Leak'
  modglia__dbbs_mod_collection__Leak__0.variant = '0'
  modglia__dbbs_mod_collection__Leak__0.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Leak__0.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Leak__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__cdp5__0
  modglia__dbbs_mod_collection__cdp5__0 = Mod()
  modglia__dbbs_mod_collection__cdp5__0.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__cdp5__0.asset_name = 'cdp5'
  modglia__dbbs_mod_collection__cdp5__0.variant = '0'
  modglia__dbbs_mod_collection__cdp5__0.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__cdp5__0.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__cdp5__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__cdp5__CR
  modglia__dbbs_mod_collection__cdp5__CR = Mod()
  modglia__dbbs_mod_collection__cdp5__CR.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__cdp5__CR.asset_name = 'cdp5'
  modglia__dbbs_mod_collection__cdp5__CR.variant = 'CR'
  modglia__dbbs_mod_collection__cdp5__CR.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__cdp5__CR.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__cdp5__CR)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Ca__granule_cell
  modglia__dbbs_mod_collection__Ca__granule_cell = Mod()
  modglia__dbbs_mod_collection__Ca__granule_cell.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Ca__granule_cell.asset_name = 'Ca'
  modglia__dbbs_mod_collection__Ca__granule_cell.variant = 'granule_cell'
  modglia__dbbs_mod_collection__Ca__granule_cell.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Ca__granule_cell.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Ca__granule_cell)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Km__granule_cell
  modglia__dbbs_mod_collection__Km__granule_cell = Mod()
  modglia__dbbs_mod_collection__Km__granule_cell.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Km__granule_cell.asset_name = 'Km'
  modglia__dbbs_mod_collection__Km__granule_cell.variant = 'granule_cell'
  modglia__dbbs_mod_collection__Km__granule_cell.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Km__granule_cell.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Km__granule_cell)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Na__granule_cell
  modglia__dbbs_mod_collection__Na__granule_cell = Mod()
  modglia__dbbs_mod_collection__Na__granule_cell.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Na__granule_cell.asset_name = 'Na'
  modglia__dbbs_mod_collection__Na__granule_cell.variant = 'granule_cell'
  modglia__dbbs_mod_collection__Na__granule_cell.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Na__granule_cell.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Na__granule_cell)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Na__granule_cell_FHF
  modglia__dbbs_mod_collection__Na__granule_cell_FHF = Mod()
  modglia__dbbs_mod_collection__Na__granule_cell_FHF.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Na__granule_cell_FHF.asset_name = 'Na'
  modglia__dbbs_mod_collection__Na__granule_cell_FHF.variant = 'granule_cell_FHF'
  modglia__dbbs_mod_collection__Na__granule_cell_FHF.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Na__granule_cell_FHF.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Na__granule_cell_FHF)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Kca11__0
  modglia__dbbs_mod_collection__Kca11__0 = Mod()
  modglia__dbbs_mod_collection__Kca11__0.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Kca11__0.asset_name = 'Kca11'
  modglia__dbbs_mod_collection__Kca11__0.variant = '0'
  modglia__dbbs_mod_collection__Kca11__0.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Kca11__0.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Kca11__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Kca22__0
  modglia__dbbs_mod_collection__Kca22__0 = Mod()
  modglia__dbbs_mod_collection__Kca22__0.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Kca22__0.asset_name = 'Kca22'
  modglia__dbbs_mod_collection__Kca22__0.variant = '0'
  modglia__dbbs_mod_collection__Kca22__0.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Kca22__0.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Kca22__0)
  #-##
  return pkg
