import os

__version__ = "0.0.0"

class Package:
  def __init__(self):
    self.mods = []

class Mod:
  pass

def package():
  pkg = Package()
  pkg.path = os.path.dirname(__file__)
  pkg.name = os.path.basename(pkg.path)
  pkg.astro_version = "0.0.4"
  pkg.glia_version = "0.1.1"

  #-Generated by Astrocyte v0.0.4
  #-modglia__dbbs_mod_collection__Leak__0
  modglia__dbbs_mod_collection__Leak__0 = Mod()
  modglia__dbbs_mod_collection__Leak__0.pkg_name = 'dbbs_mod_collection'
  modglia__dbbs_mod_collection__Leak__0.asset_name = 'Leak'
  modglia__dbbs_mod_collection__Leak__0.variant = '0'
  modglia__dbbs_mod_collection__Leak__0.namespace = 'glia__dbbs_mod_collection'
  modglia__dbbs_mod_collection__Leak__0.pkg = pkg
  pkg.mods.append(modglia__dbbs_mod_collection__Leak__0)
  #-##
  return pkg
