import os

__version__ = "0.0.2"

class Package:
  def __init__(self):
    self.mods = []

class Mod:
  pass

def package():
  pkg = Package()
  pkg.path = os.path.dirname(__file__)
  pkg.name = os.path.basename(pkg.path)
  pkg.astro_version = "0.0.4"
  pkg.glia_version = "0.1.1"
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Ca__granule_cell
  mod_glia__dbbs_mod_collection__Ca__granule_cell = Mod()
  mod_glia__dbbs_mod_collection__Ca__granule_cell.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Ca__granule_cell.asset_name = 'Ca'
  mod_glia__dbbs_mod_collection__Ca__granule_cell.variant = 'granule_cell'
  mod_glia__dbbs_mod_collection__Ca__granule_cell.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Ca__granule_cell.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Ca__granule_cell)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Cav2_2__0
  mod_glia__dbbs_mod_collection__Cav2_2__0 = Mod()
  mod_glia__dbbs_mod_collection__Cav2_2__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav2_2__0.asset_name = 'Cav2_2'
  mod_glia__dbbs_mod_collection__Cav2_2__0.variant = '0'
  mod_glia__dbbs_mod_collection__Cav2_2__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav2_2__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Cav2_2__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Cav2_3__0
  mod_glia__dbbs_mod_collection__Cav2_3__0 = Mod()
  mod_glia__dbbs_mod_collection__Cav2_3__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav2_3__0.asset_name = 'Cav2_3'
  mod_glia__dbbs_mod_collection__Cav2_3__0.variant = '0'
  mod_glia__dbbs_mod_collection__Cav2_3__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav2_3__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Cav2_3__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Cav3_1__0
  mod_glia__dbbs_mod_collection__Cav3_1__0 = Mod()
  mod_glia__dbbs_mod_collection__Cav3_1__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav3_1__0.asset_name = 'Cav3_1'
  mod_glia__dbbs_mod_collection__Cav3_1__0.variant = '0'
  mod_glia__dbbs_mod_collection__Cav3_1__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Cav3_1__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Cav3_1__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__cdp5__0
  mod_glia__dbbs_mod_collection__cdp5__0 = Mod()
  mod_glia__dbbs_mod_collection__cdp5__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__cdp5__0.asset_name = 'cdp5'
  mod_glia__dbbs_mod_collection__cdp5__0.variant = '0'
  mod_glia__dbbs_mod_collection__cdp5__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__cdp5__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__cdp5__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__cdp5__CR
  mod_glia__dbbs_mod_collection__cdp5__CR = Mod()
  mod_glia__dbbs_mod_collection__cdp5__CR.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__cdp5__CR.asset_name = 'cdp5'
  mod_glia__dbbs_mod_collection__cdp5__CR.variant = 'CR'
  mod_glia__dbbs_mod_collection__cdp5__CR.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__cdp5__CR.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__cdp5__CR)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Hcn1__0
  mod_glia__dbbs_mod_collection__Hcn1__0 = Mod()
  mod_glia__dbbs_mod_collection__Hcn1__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Hcn1__0.asset_name = 'Hcn1'
  mod_glia__dbbs_mod_collection__Hcn1__0.variant = '0'
  mod_glia__dbbs_mod_collection__Hcn1__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Hcn1__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Hcn1__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Hcn2__0
  mod_glia__dbbs_mod_collection__Hcn2__0 = Mod()
  mod_glia__dbbs_mod_collection__Hcn2__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Hcn2__0.asset_name = 'Hcn2'
  mod_glia__dbbs_mod_collection__Hcn2__0.variant = '0'
  mod_glia__dbbs_mod_collection__Hcn2__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Hcn2__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Hcn2__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kca1_1__0
  mod_glia__dbbs_mod_collection__Kca1_1__0 = Mod()
  mod_glia__dbbs_mod_collection__Kca1_1__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kca1_1__0.asset_name = 'Kca1_1'
  mod_glia__dbbs_mod_collection__Kca1_1__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kca1_1__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kca1_1__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kca1_1__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kca2_2__0
  mod_glia__dbbs_mod_collection__Kca2_2__0 = Mod()
  mod_glia__dbbs_mod_collection__Kca2_2__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kca2_2__0.asset_name = 'Kca2_2'
  mod_glia__dbbs_mod_collection__Kca2_2__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kca2_2__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kca2_2__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kca2_2__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kir2_3__0
  mod_glia__dbbs_mod_collection__Kir2_3__0 = Mod()
  mod_glia__dbbs_mod_collection__Kir2_3__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kir2_3__0.asset_name = 'Kir2_3'
  mod_glia__dbbs_mod_collection__Kir2_3__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kir2_3__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kir2_3__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kir2_3__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Km__granule_cell
  mod_glia__dbbs_mod_collection__Km__granule_cell = Mod()
  mod_glia__dbbs_mod_collection__Km__granule_cell.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Km__granule_cell.asset_name = 'Km'
  mod_glia__dbbs_mod_collection__Km__granule_cell.variant = 'granule_cell'
  mod_glia__dbbs_mod_collection__Km__granule_cell.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Km__granule_cell.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Km__granule_cell)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv7__0
  mod_glia__dbbs_mod_collection__Kv7__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv7__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv7__0.asset_name = 'Kv7'
  mod_glia__dbbs_mod_collection__Kv7__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv7__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv7__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv7__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv1_1__0
  mod_glia__dbbs_mod_collection__Kv1_1__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv1_1__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv1_1__0.asset_name = 'Kv1_1'
  mod_glia__dbbs_mod_collection__Kv1_1__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv1_1__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv1_1__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv1_1__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv1_5__0
  mod_glia__dbbs_mod_collection__Kv1_5__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv1_5__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv1_5__0.asset_name = 'Kv1_5'
  mod_glia__dbbs_mod_collection__Kv1_5__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv1_5__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv1_5__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv1_5__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv2_2__0
  mod_glia__dbbs_mod_collection__Kv2_2__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv2_2__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv2_2__0.asset_name = 'Kv2_2'
  mod_glia__dbbs_mod_collection__Kv2_2__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv2_2__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv2_2__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv2_2__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv3_3__0
  mod_glia__dbbs_mod_collection__Kv3_3__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv3_3__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv3_3__0.asset_name = 'Kv3_3'
  mod_glia__dbbs_mod_collection__Kv3_3__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv3_3__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv3_3__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv3_3__0)
  #-##
  #-Generated by Astrocyte v0.0.4
  #-mod_glia__dbbs_mod_collection__Kv3_4__0
  mod_glia__dbbs_mod_collection__Kv3_4__0 = Mod()
  mod_glia__dbbs_mod_collection__Kv3_4__0.pkg_name = 'dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv3_4__0.asset_name = 'Kv3_4'
  mod_glia__dbbs_mod_collection__Kv3_4__0.variant = '0'
  mod_glia__dbbs_mod_collection__Kv3_4__0.namespace = 'glia__dbbs_mod_collection'
  mod_glia__dbbs_mod_collection__Kv3_4__0.pkg = pkg
  pkg.mods.append(mod_glia__dbbs_mod_collection__Kv3_4__0)
  #-##
  return pkg
